### ISSUE TITLE
rebase on top of the ethminer master branch

### ISSUE THREAD

**Issue by hackmod** [ifdefelse/ProgPOW#17]
***Experimental***

This is my rebase work on top of the latest ethminer master branch.
The master branch of the ethminer a bit faster and the latest [ethash](https://github.com/chfast/ethash) already support ProgPoW v0.9.1

Please see
https://github.com/EthersocialNetwork/ethminer-ProgPOW/commits/progpow-master-rebase

***Only CUDA tested.***

## Screen shot
(rebased ProgPoW ethminer + chfast/ethash master branch with a small progpow CPU verifier wrapper fix)
![image](https://user-images.githubusercontent.com/32324335/48892861-58eebc00-ee82-11e8-96f6-8c357505fc19.png)

![image](https://user-images.githubusercontent.com/32324335/48893038-baaf2600-ee82-11e8-8f61-dfca3c6a75d8.png)
P106-6G (samsung) ~10.4MH/s (~24.0MH/s for ethash)

**Comment by naikmyeong** [comment]
### CI test results:

+ https://circleci.com/gh/ethereum-mining/ethminer/2535?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

+ https://ci.appveyor.com/project/ethereum-mining/ethminer/builds/20492596/job/1drp6imtv7o4o033

+ https://travis-ci.org/ethereum-mining/ethminer/jobs/458471141

### log:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_nvrtc_LIBRARY
    linked by target "ethash-cuda" in directory C:/projects/ethminer/libethash-cuda
-- Configuring incomplete, errors occurred!
```

I think CMake can't find the specific library that is defined here

https://github.com/EthersocialNetwork/ethminer-ProgPOW/blame/master/libethash-cuda/CMakeLists.txt#L42

**Comment by hackmod** [comment]
@naikmyeong // fixed now
anyway, the openCL version have some `period_seed` issue

**Comment by hackmod** [comment]
rebased again on top of the latest master branch https://github.com/ethereum-mining/ethminer/pull/1766

**Comment by hackmod** [comment]
updated. rebased again~
support CUDA-8 (compiled. not tested)/CUDA-9/CUDA-10

**Comment by hackmod** [comment]
binaries are available at https://github.com/hackmod/ethminer/releases/tag/v0.9.2-progpow

- ***only CUDA supported***
- you can test it locally with `--noevel` option like as follow
`ethminer --noeval -v 3 --cuda-devices 0 -U -P http://127.0.0.1:8545`

See also progpow testnet:
 - netstats - http://boot.gangnam.ethdevops.io/
 - https://gist.github.com/holiman/c8944c8be26f798e391822b9a70cb91c#gistcomment-2783941

**Comment by hackmod** [comment]
https://github.com/hackmod/ethminer/releases/tag/v0.9.2-opencl-win-1218
***OpenCL supported now***
- extract `compileKernel()` routine and call `compileKernel(prog_seed)` like as `CUDAMiner`
- CUDA-8 support added (GTX 680 confirmed)
- temporally disable CUDA to strip `nvrtc*.(so|dll)` defendency

**Comment by hackmod** [comment]
fixed epoch change issue
https://github.com/hackmod/ethminer/releases/tag/v0.9.2-opencl-win-1219
- OpenCL: fixed setArg issue after epoch change
- CUDA: fixed manual rebase mistake. (fix `incompatible driver context` error after epoch change)

**Comment by ifdefelse** [comment]
Considering https://github.com/AndreaLanfranchi/ethminer is close to ethash master and runs both ethash and progpow I think we can close this out as fixed.  Thanks for all the work.

**Comment by solardiz** [comment]
@ifdefelse What's your desired/expected future for this repo vs. https://github.com/AndreaLanfranchi/ethminer? ProgPOW is still being revised in this repo, yet in a tree based off older ethminer. Is the intended use of this repo to serve as reference and for testing? Should those ProgPOW spec and implementation changes be getting ported to https://github.com/AndreaLanfranchi/ethminer and at what points? Thanks!

**Comment by ifdefelse** [comment]
This repro is only intended for algorithm research and development.  Andrea's implementation is up-to-date and much more polished for going into production.
